project_id = "wqpoozpbceucynsojmbk"

# API and Database Configuration
[api]
# Primary database settings
db_url = "https://wqpoozpbceucynsojmbk.supabase.co"

# JWT Settings
[auth]
jwt_expiry = 3600 # Access token expiry time in seconds

# Data API Settings
[api.schemas]
# Exposed schemas
public = true
graphql_public = true

[api.rest]
# Extra search path
extra_search_path = "public, extensions"
# Max rows returned from a view, table, or stored procedure
max_rows = 1000