
project_id = "wqpoozpbceucynsojmbk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

# Fix the migration configuration format
[db.migration]
# Use string path rather than nested directory structure 
path = "migrations"

[studio]
enabled = true
port = 54323
