
project_id = "wqpoozpbceucynsojmbk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[[db.migration.directories]]
path = "migrations"

[studio]
enabled = true
port = 54323
