#!/bin/bash

# 🇳🇴 SNAKKAZ EMERGENCY FIX COMMANDS FOR CPANEL TERMINAL

echo "🚨 EMERGENCY FIX SEQUENCE FOR MCP SERVER"
echo "========================================"

echo ""
echo "🔧 OPTION 1: Quick .cjs Fix (Recommended)"
echo "cd /home/snakqsqe/mcp.snakkaz.com/"
echo "mv simplified-server.js simplified-server.cjs"
echo "# Then update cPanel startup file to: simplified-server.cjs"
echo ""

echo "🔧 OPTION 2: Fix package.json"
echo "cd /home/snakqsqe/mcp.snakkaz.com/"
echo "cp package.json package.json.backup"
echo "sed -i '/\"type\": \"module\"/d' package.json"
echo "node simplified-server.js"
echo ""

echo "🔧 OPTION 3: Convert back to ES6 imports"
echo "cat > simplified-server.js << 'EOF'"
echo "import express from 'express';"
echo "import cors from 'cors';"
echo "import { createServer } from 'http';"
echo "import { fileURLToPath } from 'url';"
echo "import { dirname, join } from 'path';"
echo ""
echo "const __filename = fileURLToPath(import.meta.url);"
echo "const __dirname = dirname(__filename);"
echo ""
echo "const app = express();"
echo ""
echo "app.use(express.json());"
echo "app.use(cors({origin: '*'}));"
echo "app.use(express.static('.'));"
echo ""
echo "app.get('/health', (req, res) => {"
echo "  res.json({status: 'ok', timestamp: new Date().toISOString()});"
echo "});"
echo ""
echo "app.get('/api/health', (req, res) => {"
echo "  res.json({status: 'ok', server: 'SnakkaZ MCP', timestamp: new Date().toISOString()});"
echo "});"
echo ""
echo "const PORT = process.env.PORT || 3000;"
echo "app.listen(PORT, () => {"
echo "  console.log(\`🚀 SnakkaZ Server running on port \${PORT}\`);"
echo "});"
echo "EOF"
echo ""

echo "📋 LIVE STATUS CHECKER FIX:"
echo "# Copy status checker to MCP subdomain too"
echo "cp /home/snakqsqe/public_html/live-status-checker.html /home/snakqsqe/mcp.snakkaz.com/"
echo ""

echo "✅ RECOMMENDED QUICK FIX:"
echo "1. mv simplified-server.js simplified-server.cjs"
echo "2. cPanel → Node.js → Edit → startup file: simplified-server.cjs"
echo "3. SAVE → RESTART"
echo "4. Test: https://mcp.snakkaz.com/api/health"
echo ""

echo "🇳🇴 Norwegian Tech Excellence - Emergency Fix!"
