#!/bin/bash
echo "🚀 SNAKKAZ QUICK DEPLOY TO CPANEL"
echo "================================="
echo ""
echo "📁 Files ready for upload:"
echo "1. snakkaz-main-site.zip → Upload to public_html"
echo "2. snakkaz-mcp-subdomain.zip → Upload to mcp.snakkaz.com"
echo ""
echo "📋 Next steps:"
echo "1. Create subdomain: mcp.snakkaz.com"  
echo "2. Upload and extract ZIP files"
echo "3. Run: cd mcp.snakkaz.com && ./start-mcp.sh"
echo "4. Test: curl https://mcp.snakkaz.com/api/health"
echo ""
echo "🇳🇴 SnakkaZ will be LIVE! 🚀"
