/**
 * SnakkaZ Supabase Integration with Design Protection
 * MCP Server Guided Implementation
 */

import { createClient } from "@supabase/supabase-js";

// Environment configuration
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error("Missing Supabase environment variables");
}

// Create Supabase client with design-friendly config
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    // Preserve design during auth flows
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // Custom auth config to prevent CSS conflicts
    flowType: "pkce",
  },
  realtime: {
    // Real-time config that won't interfere with design
    params: {
      eventsPerSecond: 10,
    },
  },
  // Global options to preserve design
  global: {
    headers: {
      "X-Client-Info": "snakkaz-liquid-glass",
    },
  },
});

// Design Protection Utilities
export const designProtection = {
  // Wrap Supabase components with protection classes
  wrapComponent: (element: HTMLElement) => {
    element.classList.add(
      "liquid-glass",
      "css-protection-lock",
      "supabase-override"
    );
    return element;
  },

  // Apply design variables to Supabase elements
  applyLiquidGlass: (selector: string) => {
    const elements = document.querySelectorAll(selector);
    elements.forEach((el) => {
      if (el instanceof HTMLElement) {
        el.style.setProperty(
          "background",
          "var(--liquid-glass-bg)",
          "important"
        );
        el.style.setProperty(
          "backdrop-filter",
          "var(--glass-blur)",
          "important"
        );
        el.style.setProperty(
          "border",
          "1px solid var(--liquid-glass-border)",
          "important"
        );
        el.style.setProperty(
          "border-radius",
          "var(--glass-border-radius)",
          "important"
        );
        el.style.setProperty("color", "var(--norwegian-white)", "important");
      }
    });
  },

  // Monitor and fix Supabase CSS conflicts
  monitorAndFix: () => {
    const observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        mutation.addedNodes.forEach((node) => {
          if (node instanceof HTMLElement) {
            // Check for Supabase elements
            if (
              node.className?.includes("supabase") ||
              node.querySelector?.('[class*="supabase"]')
            ) {
              console.log("🛡️ Applying design protection to Supabase element");
              designProtection.applyLiquidGlass(node.tagName.toLowerCase());
            }
          }
        });
      });
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
    });

    return observer;
  },
};

// Database Types (Generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          full_name: string;
          avatar_url: string;
          created_at: string;
          updated_at: string;
          pin_preferences: any;
          is_admin: boolean;
        };
        Insert: {
          id: string;
          username: string;
          full_name?: string;
          avatar_url?: string;
          pin_preferences?: any;
          is_admin?: boolean;
        };
        Update: {
          username?: string;
          full_name?: string;
          avatar_url?: string;
          pin_preferences?: any;
          is_admin?: boolean;
        };
      };
      chat_rooms: {
        Row: {
          id: string;
          name: string;
          description: string;
          created_at: string;
          updated_at: string;
          created_by: string;
          is_private: boolean;
          max_members: number;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string;
          created_by: string;
          is_private?: boolean;
          max_members?: number;
        };
        Update: {
          name?: string;
          description?: string;
          is_private?: boolean;
          max_members?: number;
        };
      };
      messages: {
        Row: {
          id: string;
          room_id: string;
          sender_id: string;
          encrypted_content: string;
          message_type: string;
          created_at: string;
          updated_at: string;
          metadata: any;
          is_edited: boolean;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          room_id: string;
          sender_id: string;
          encrypted_content: string;
          message_type?: string;
          metadata?: any;
          is_edited?: boolean;
          is_deleted?: boolean;
        };
        Update: {
          encrypted_content?: string;
          message_type?: string;
          metadata?: any;
          is_edited?: boolean;
          is_deleted?: boolean;
        };
      };
    };
  };
}

// Initialize design protection
designProtection.monitorAndFix();

console.log("✅ SnakkaZ Supabase client initialized with design protection");
console.log("🎨 Liquid Glass design system preserved");
console.log("🛡️ CSS protection monitoring active");
