#!/bin/bash

# hosting-config-instructions.sh
# Instructions for hosting provider to configure subdomain document roots

echo "=============================================="
echo "   SNAKKAZ CHAT SUBDOMAIN CONFIGURATION"
echo "=============================================="
echo ""
echo "🎯 HOSTING PROVIDER CONFIGURATION NEEDED"
echo ""
echo "Current Issue:"
echo "- All subdomains show LiteSpeed directory listing"
echo "- Subdomains point to /public_html/ instead of subdomain directories"
echo ""
echo "Required Configuration:"
echo "========================"
echo ""
echo "IN CPANEL -> SUBDOMAINS SECTION:"
echo ""
echo "1. dash.snakkaz.com"
echo "   Document Root: /public_html/dash/"
echo ""
echo "2. business.snakkaz.com" 
echo "   Document Root: /public_html/business/"
echo ""
echo "3. docs.snakkaz.com"
echo "   Document Root: /public_html/docs/"
echo ""
echo "4. analytics.snakkaz.com"
echo "   Document Root: /public_html/analytics/"
echo ""
echo "5. mcp.snakkaz.com"
echo "   Document Root: /public_html/mcp/"
echo ""
echo "6. help.snakkaz.com"
echo "   Document Root: /public_html/help/"
echo ""
echo "=============================================="
echo "   VERIFICATION AFTER CONFIGURATION"
echo "=============================================="
echo ""
echo "After configuration, each subdomain should:"
echo "✅ Serve the Snakkaz Chat React application"
echo "✅ Show unique titles (e.g., 'Snakkaz Chat - Dashboard')"
echo "✅ Display subdomain-specific content"
echo ""
echo "Test commands:"
echo "curl -s https://dash.snakkaz.com | grep -i 'snakkaz'"
echo "curl -s https://business.snakkaz.com | grep -i 'snakkaz'"
echo ""
echo "=============================================="
echo "   FILES ALREADY DEPLOYED"
echo "=============================================="
echo ""
echo "✅ All React app files uploaded to:"
echo "   /public_html/dash/"
echo "   /public_html/business/"
echo "   /public_html/docs/"
echo "   /public_html/analytics/"
echo "   /public_html/mcp/"
echo "   /public_html/help/"
echo ""
echo "✅ Each directory contains:"
echo "   - index.html (React app entry point)"
echo "   - assets/ directory (JS, CSS, images)"
echo "   - .htaccess (React Router configuration)"
echo ""
echo "⏱️ Estimated configuration time: 15 minutes"
echo "🎯 Result: 100% functional subdomain system"
echo ""
