#!/bin/bash
# security-hardening.sh - Comprehensive security hardening for Snakkaz Chat
# This script implements multiple security layers to protect against attacks

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=============================================${NC}"
echo -e "${BLUE}     Snakkaz Chat Security Hardening        ${NC}"
echo -e "${BLUE}=============================================${NC}"
echo

# Create .htaccess file for additional security
echo -e "${BLUE}Creating security .htaccess file...${NC}"
cat > dist/.htaccess << 'EOF'
# Snakkaz Chat Security Headers and Rules
# Generated by security-hardening.sh

# Security Headers
<IfModule mod_headers.c>
    # Content Security Policy
    Header always set Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://*.supabase.io; frame-ancestors 'none';"
    
    # Additional Security Headers
    Header always set X-Frame-Options "DENY"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-XSS-Protection "1; mode=block"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    
    # Remove server information
    Header always unset Server
    Header always unset X-Powered-By
    
    # HSTS for HTTPS enforcement
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
</IfModule>

# Block common attack patterns
<IfModule mod_rewrite.c>
    RewriteEngine On
    
    # Block suspicious user agents
    RewriteCond %{HTTP_USER_AGENT} (bot|crawler|spider|scraper|harvester|scanner) [NC]
    RewriteRule .* - [F,L]
    
    # Block SQL injection attempts
    RewriteCond %{QUERY_STRING} (union|select|insert|update|delete|drop|create|alter|exec|script) [NC]
    RewriteRule .* - [F,L]
    
    # Block XSS attempts
    RewriteCond %{QUERY_STRING} (<script|javascript:|vbscript:|onload|onerror|onclick) [NC]
    RewriteRule .* - [F,L]
    
    # Block file inclusion attempts
    RewriteCond %{QUERY_STRING} (\.\./|\.\.\.\./|/etc/passwd|/proc/|/bin/|/usr/bin/) [NC]
    RewriteRule .* - [F,L]
    
    # Rate limiting - block requests with more than 30 requests per minute from same IP
    RewriteMap requests "prg:/usr/bin/rate_limit.sh"
    RewriteCond ${requests:%{REMOTE_ADDR}} >30
    RewriteRule .* - [F,L]
</IfModule>

# Disable directory browsing
Options -Indexes

# Protect sensitive files
<Files "*.env">
    Require all denied
</Files>

<Files "*.log">
    Require all denied
</Files>

<Files "package.json">
    Require all denied
</Files>

<Files "*.config.js">
    Require all denied
</Files>

# Block access to common admin paths that don't exist in our app
RedirectMatch 403 ^/wp-admin/
RedirectMatch 403 ^/admin/
RedirectMatch 403 ^/phpMyAdmin/
RedirectMatch 403 ^/phpmyadmin/
RedirectMatch 403 ^/mysql/
RedirectMatch 403 ^/cpanel/
RedirectMatch 403 ^/cgi-bin/

# Cache control for security
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType text/html "access plus 0 seconds"
    ExpiresByType application/json "access plus 0 seconds"
</IfModule>

# Compress files for better performance
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/plain
    AddOutputFilterByType DEFLATE text/html
    AddOutputFilterByType DEFLATE text/css
    AddOutputFilterByType DEFLATE application/javascript
    AddOutputFilterByType DEFLATE application/json
</IfModule>

# Redirect HTTP to HTTPS
<IfModule mod_rewrite.c>
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

EOF

echo -e "${GREEN}✅ Security .htaccess file created${NC}"

# Create robots.txt to control bot access
echo -e "${BLUE}Creating robots.txt...${NC}"
cat > dist/robots.txt << 'EOF'
# Snakkaz Chat - Robots Control
User-agent: *
Disallow: /api/
Disallow: /admin/
Disallow: /login
Disallow: /premium
Disallow: /chat
Disallow: /*.json
Disallow: /*.env
Disallow: /*.log

# Allow access to public info pages
Allow: /
Allow: /info

# Crawl delay to prevent aggressive scraping
Crawl-delay: 10

# Sitemap
Sitemap: https://www.snakkaz.com/sitemap.xml
EOF

echo -e "${GREEN}✅ Robots.txt created${NC}"

# Create security.txt for responsible disclosure
echo -e "${BLUE}Creating security.txt...${NC}"
mkdir -p dist/.well-known
cat > dist/.well-known/security.txt << 'EOF'
Contact: security@snakkaz.com
Expires: 2025-12-31T23:59:59.000Z
Preferred-Languages: no, en
Canonical: https://www.snakkaz.com/.well-known/security.txt

# Security Policy for Snakkaz Chat
# We appreciate responsible disclosure of security vulnerabilities

# What we protect:
# - User data and privacy
# - Chat encryption and security
# - Authentication systems
# - Payment processing

# Out of scope:
# - Social engineering
# - Physical attacks
# - DDoS attacks
# - Third-party services beyond our control

# Reward: Recognition and appreciation for valid findings
EOF

echo -e "${GREEN}✅ Security.txt created${NC}"

# Create IP blocking list
echo -e "${BLUE}Creating IP security rules...${NC}"
cat > dist/.htaccess.security << 'EOF'
# Additional IP-based security rules
# Include this in main .htaccess if needed

<RequireAll>
    Require all granted
    
    # Block known malicious IP ranges
    Require not ip 192.168.1.0/24
    
    # Block specific countries if needed (uncomment as needed)
    # Require not env GEOIP_COUNTRY_CODE=CN
    # Require not env GEOIP_COUNTRY_CODE=RU
    
    # Allow Norwegian IPs with higher priority
    # Require env GEOIP_COUNTRY_CODE=NO
</RequireAll>

# Rate limiting per IP (if mod_security is available)
<IfModule mod_security2.c>
    SecRule IP:DOS_COUNTER "@gt 30" "id:1001,phase:1,deny,msg:'Rate limited - too many requests'"
    SecAction "id:1002,phase:1,setvar:IP.DOS_COUNTER=+1,expirevar:IP.DOS_COUNTER=60"
</IfModule>
EOF

echo -e "${GREEN}✅ IP security rules created${NC}"

# Create monitoring script
echo -e "${BLUE}Creating security monitoring script...${NC}"
cat > security-monitor.sh << 'EOF'
#!/bin/bash
# security-monitor.sh - Monitor for security threats

LOG_FILE="security.log"
DATE=$(date "+%Y-%m-%d %H:%M:%S")

# Function to log security events
log_security_event() {
    echo "[$DATE] SECURITY: $1" >> $LOG_FILE
    echo "Security event logged: $1"
}

# Check for suspicious activity in web logs
check_access_logs() {
    if [ -f "/var/log/apache2/access.log" ]; then
        # Check for SQL injection attempts
        SQLI_COUNT=$(grep -c "union\|select\|drop\|insert" /var/log/apache2/access.log | tail -1000)
        if [ "$SQLI_COUNT" -gt 10 ]; then
            log_security_event "High number of SQL injection attempts detected: $SQLI_COUNT"
        fi
        
        # Check for XSS attempts
        XSS_COUNT=$(grep -c "script\|javascript\|alert" /var/log/apache2/access.log | tail -1000)
        if [ "$XSS_COUNT" -gt 5 ]; then
            log_security_event "XSS attempts detected: $XSS_COUNT"
        fi
        
        # Check for 404 scanning
        SCAN_COUNT=$(grep " 404 " /var/log/apache2/access.log | tail -1000 | wc -l)
        if [ "$SCAN_COUNT" -gt 50 ]; then
            log_security_event "Potential directory scanning detected: $SCAN_COUNT 404s"
        fi
    fi
}

# Check disk space for potential DoS
check_disk_space() {
    DISK_USAGE=$(df / | awk 'NR==2{print $5}' | sed 's/%//')
    if [ "$DISK_USAGE" -gt 90 ]; then
        log_security_event "Disk usage critical: ${DISK_USAGE}% - potential DoS"
    fi
}

# Check for failed login attempts (if using fail2ban)
check_failed_logins() {
    if command -v fail2ban-client &> /dev/null; then
        BANNED_IPS=$(fail2ban-client status sshd | grep "Banned IP list" | wc -w)
        if [ "$BANNED_IPS" -gt 5 ]; then
            log_security_event "High number of banned IPs: $BANNED_IPS"
        fi
    fi
}

# Run checks
echo "Running security monitoring..."
check_access_logs
check_disk_space
check_failed_logins

echo "Security monitoring complete. Check $LOG_FILE for events."
EOF

chmod +x security-monitor.sh
echo -e "${GREEN}✅ Security monitoring script created${NC}"

# Create CAPTCHA implementation guide
echo -e "${BLUE}Creating CAPTCHA implementation guide...${NC}"
cat > CAPTCHA-IMPLEMENTATION.md << 'EOF'
# CAPTCHA Implementation for Snakkaz Chat

## Overview
To protect against automated attacks and bot spam, implement CAPTCHA verification on sensitive forms.

## Recommended Solutions

### 1. hCaptcha (Privacy-focused)
```javascript
// Install: npm install @hcaptcha/react-hcaptcha
import HCaptcha from '@hcaptcha/react-hcaptcha';

function LoginForm() {
  const [captchaToken, setCaptchaToken] = useState(null);
  
  return (
    <form>
      {/* Other form fields */}
      <HCaptcha
        sitekey="your-hcaptcha-site-key"
        onVerify={setCaptchaToken}
      />
      <button disabled={!captchaToken}>Submit</button>
    </form>
  );
}
```

### 2. Cloudflare Turnstile (Free)
```javascript
// Install: npm install @cloudflare/turnstile
import { Turnstile } from '@cloudflare/turnstile';

function RegistrationForm() {
  const [turnstileToken, setTurnstileToken] = useState(null);
  
  return (
    <form>
      {/* Other form fields */}
      <Turnstile
        siteKey="your-turnstile-site-key"
        onSuccess={setTurnstileToken}
      />
      <button disabled={!turnstileToken}>Register</button>
    </form>
  );
}
```

### 3. Custom Mathematical CAPTCHA
```javascript
function MathCaptcha() {
  const [num1] = useState(Math.floor(Math.random() * 10) + 1);
  const [num2] = useState(Math.floor(Math.random() * 10) + 1);
  const [userAnswer, setUserAnswer] = useState('');
  
  const isCorrect = parseInt(userAnswer) === (num1 + num2);
  
  return (
    <div>
      <label>Løs regnestykket: {num1} + {num2} = ?</label>
      <input
        type="number"
        value={userAnswer}
        onChange={(e) => setUserAnswer(e.target.value)}
        placeholder="Svar"
      />
      {userAnswer && (
        <span style={{color: isCorrect ? 'green' : 'red'}}>
          {isCorrect ? '✓ Riktig' : '✗ Feil'}
        </span>
      )}
    </div>
  );
}
```

## Implementation Priority

1. **Login Form** - Prevent brute force attacks
2. **Registration Form** - Prevent fake account creation
3. **Password Reset** - Prevent enumeration attacks
4. **Contact Forms** - Prevent spam
5. **Premium Upgrade** - Prevent fraudulent transactions

## Backend Verification

Always verify CAPTCHA tokens on the server:

```javascript
// Express.js example
app.post('/api/login', async (req, res) => {
  const { email, password, captchaToken } = req.body;
  
  // Verify CAPTCHA first
  const captchaValid = await verifyCaptcha(captchaToken);
  if (!captchaValid) {
    return res.status(400).json({ error: 'CAPTCHA verification failed' });
  }
  
  // Proceed with login
  // ...
});
```

## Rate Limiting Enhancement

Combine CAPTCHA with rate limiting:

```javascript
const rateLimit = require('express-rate-limit');

const loginLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 5, // 5 attempts per window
  message: 'Too many login attempts, please try again later',
  standardHeaders: true,
  legacyHeaders: false,
});

app.post('/api/login', loginLimiter, async (req, res) => {
  // Handle login with CAPTCHA
});
```
EOF

echo -e "${GREEN}✅ CAPTCHA implementation guide created${NC}"

# Create comprehensive security checklist
echo -e "${BLUE}Creating security checklist...${NC}"
cat > SECURITY-CHECKLIST.md << 'EOF'
# Snakkaz Chat Security Checklist

## ✅ Completed Security Measures

### Authentication & Authorization
- [x] Secure login with email/password
- [x] Password strength requirements
- [x] Protected routes requiring authentication
- [x] Premium access verification
- [x] Account lockout after failed attempts
- [x] Session management with Supabase

### Data Protection
- [x] End-to-end encryption for chat messages
- [x] Sensitive configuration hidden from public
- [x] User data stored securely in Supabase
- [x] Environment variables for secrets

### Infrastructure Security
- [x] HTTPS enforcement
- [x] Security headers (CSP, HSTS, etc.)
- [x] Directory browsing disabled
- [x] Sensitive files blocked (.env, logs)
- [x] Bot protection with robots.txt

## 🔄 In Progress

### Anti-Bot & Spam Protection
- [ ] CAPTCHA on login form
- [ ] CAPTCHA on registration form
- [ ] Rate limiting implementation
- [ ] IP-based blocking for suspicious activity

### Monitoring & Logging
- [ ] Security event logging
- [ ] Failed login attempt monitoring
- [ ] Suspicious activity detection
- [ ] Regular security audits

## 📋 Next Steps (Priority Order)

### High Priority
1. **Implement CAPTCHA** - Prevent automated attacks
2. **Add Rate Limiting** - Prevent brute force and spam
3. **Set up Security Monitoring** - Detect attacks in real-time
4. **IP Reputation Checking** - Block known malicious IPs

### Medium Priority
5. **Two-Factor Authentication** - Enhanced user security
6. **Content Security Policy** - Prevent XSS attacks
7. **Input Validation** - Sanitize all user inputs
8. **Regular Security Updates** - Keep dependencies current

### Low Priority
9. **Penetration Testing** - Professional security assessment
10. **Security Audit Logging** - Compliance and forensics
11. **DDoS Protection** - Use Cloudflare or similar
12. **Backup Encryption** - Secure data backups

## 🛡️ Security Best Practices

### For Users
- Strong passwords with mixed characters
- Enable 2FA when available
- Regular password updates
- Secure device usage

### For Developers
- Regular dependency updates
- Code review for security issues
- Principle of least privilege
- Defense in depth strategy

### For Operations
- Regular backups with encryption
- Security monitoring and alerting
- Incident response procedures
- Regular security training

## 🚨 Security Incident Response

### If Security Breach Detected:
1. **Immediate Response**
   - Isolate affected systems
   - Preserve evidence
   - Document incident

2. **Investigation**
   - Determine scope of breach
   - Identify attack vector
   - Assess data exposure

3. **Recovery**
   - Patch vulnerabilities
   - Restore from clean backups
   - Reset affected credentials

4. **Post-Incident**
   - Update security measures
   - User notification if required
   - Lessons learned documentation

## 📞 Security Contacts

- **Security Email**: security@snakkaz.com
- **Emergency Response**: Follow incident response plan
- **Vulnerability Reports**: Use security.txt guidelines

## 🔄 Regular Review Schedule

- **Weekly**: Security logs review
- **Monthly**: Dependency updates
- **Quarterly**: Security assessment
- **Annually**: Full security audit
EOF

echo -e "${GREEN}✅ Security checklist created${NC}"

echo -e "\n${GREEN}==================================================${NC}"
echo -e "${GREEN}     Security Hardening Complete!                 ${NC}"
echo -e "${GREEN}==================================================${NC}"
echo
echo -e "Security measures implemented:"
echo -e "✅ Security headers and .htaccess rules"
echo -e "✅ Bot protection with robots.txt"
echo -e "✅ Security disclosure policy"
echo -e "✅ Monitoring scripts and procedures"
echo -e "✅ CAPTCHA implementation guide"
echo -e "✅ Comprehensive security checklist"
echo
echo -e "${YELLOW}Next immediate steps:${NC}"
echo -e "1. Deploy the updated application with security measures"
echo -e "2. Implement CAPTCHA on login/registration forms"
echo -e "3. Set up monitoring and alerting"
echo -e "4. Review and test all security measures"
echo
echo -e "${BLUE}Run: ./security-monitor.sh to start security monitoring${NC}"
