# Supabase Project Configuration
project_id = "your-project-id"
organization_id = "your-organization-id"

[api]
# This is the port the API server will listen on
port = 54321
schemas = ["public", "storage", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
# The port the database will listen on
port = 54322
major_version = 15

[studio]
# The port Studio will listen on
port = 54323

[inbucket]
# The port Inbucket will listen on
port = 54324

[auth]
# The port the Auth server will listen on
port = 54325

[storage]
# The port the Storage server will listen on
port = 54326

[realtime]
# The port the Realtime server will listen on
port = 54327

[functions]
[functions.serve]
port = 54328
